
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package travel.client;

import java.util.logging.Logger;
import javax.jws.WebService;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2023-04-14T17:36:00.986+03:00
 * Generated source version: 3.5.5
 *
 */

@javax.jws.WebService(
                      serviceName = "TravelService",
                      portName = "TravelPort",
                      targetNamespace = "http://www.travel",
                      wsdlLocation = "file:/C:/Users/etudiant/Documents/Eclipse/travelagent/src/main/webapp/wsdl/travel.wsdl",
                      endpointInterface = "travel.client.Travel")

public class TravelPortImpl implements Travel {

    private static final Logger LOG = Logger.getLogger(TravelPortImpl.class.getName());

}
