package travel.client;

import javax.jws.WebService;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2023-04-14T17:36:00.996+03:00
 * Generated source version: 3.5.5
 *
 */
@WebService(targetNamespace = "http://www.travel", name = "Travel")
public interface Travel {
}
