
package travel.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebService;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2023-04-14T17:36:00.879+03:00
 * Generated source version: 3.5.5
 *
 */
public final class Travel_TravelPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.travel", "TravelService");

    private Travel_TravelPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TravelService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        TravelService ss = new TravelService(wsdlURL, SERVICE_NAME);
        Travel port = ss.getTravelPort();


        System.exit(0);
    }

}
